name: navigation_drawer_example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  sleek_circular_slider: ^2.0.1
  vector_math: ^2.1.1
  flutter_local_notifications: ^9.2.0
  rxdart: ^0.27.1
  flutter_native_timezone: ^2.0.0
  fl_chart: ^0.40.6
  flutter:
    sdk: flutter
  analog_clock: 

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.10
  intl: ^0.17.0
  numberpicker: ^2.1.1
  firebase_core_web: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  